solr:
  image: urosmarolt/mysolr
  ports:
    - "8983:8983"
db:
  image: postgres
web:
  build: .
  command: python manage.py runserver_plus 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
    - solr