# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default='static/uploads/douche1.jpg', upload_to='static/uploads'),
        ),
        migrations.AddField(
            model_name='review',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='static/thumbnails/douche1.jpg', upload_to='static/thumbnails'),
        ),
    ]
