# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160502_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='blog/static/uploads/douche1.jpg', upload_to='blog/static/uploads'),
        ),
        migrations.AlterField(
            model_name='review',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='blog/static/thumbnails/douche1.jpg', upload_to='static/thumbnails'),
        ),
    ]
