# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 17:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_review_review_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='general_info',
        ),
        migrations.AddField(
            model_name='review',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, max_length=100000, to='blog.Post', verbose_name='list of items'),
        ),
        migrations.AddField(
            model_name='review',
            name='ratings',
            field=models.TextField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(default=datetime.datetime(2016, 5, 7, 17, 44, 50, 564431, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
