# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160507_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='exclusive_bonus',
            field=models.TextField(default='Exclusive Bonus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='freespins',
            field=models.TextField(default='Freespins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='match_bonus',
            field=models.TextField(default='Match bonus %'),
            preserve_default=False,
        ),
    ]
