# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(max_length=200),
        ),
    ]
