# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20160514_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='meta_keywords',
            field=models.CharField(default='Meta Keywords', max_length=200),
        ),
    ]
