# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160514_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slider',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
