# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_review_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.IntegerField(default=10),
        ),
    ]
