# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20160522_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('page', 'Page')], default='post', max_length=10),
        ),
    ]
