# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.TextField(),
        ),
    ]
