# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20160525_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='featured_text',
            field=models.TextField(default='Featured text'),
        ),
    ]
